name = "xiaobuting-wanbiying"
main = "src/index.ts"
compatibility_date = "2024-01-15"

[vars]
BOT_TOKEN = "8496818925:AAGxeh_UWELR9iGH9lEhuKbnNHcPLUDu6k0"
BOT_USERNAME = "XBTyxbot"
WEBAPP_URL = "https://beijingshunyi.github.io/Telegram-xiaobuting-wanbiying"
SUPABASE_URL = "https://mtndxfqxivgivbwamjgn.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10bmR4ZnF4aXZnaXZid2FtamduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNDc1MDQsImV4cCI6MjA3MzgyMzUwNH0.s7LQxin9OyNLUTQsrv0EK1z60CcmqhyGAjDY-A17Yy0"

[secrets]
SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10bmR4ZnF4aXZnaXZid2FtamduIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1ODI0NzUwNCwiZXhwIjoyMDczODIzNTA0fQ.zBPORwIitvB40av6G05c_Qi6BmdKOEvtQk3gs-QCjLA"